import type { ScriptDefinition } from './types.js'

const discussionTools = [
  'send_message',
  'ask_player',
  'reply_question',
  'decline_question',
  'yield_turn',
  'finish_round',
] as const

export const seventhPierV2: ScriptDefinition = {
  id: 'seventh-pier',
  version: '2.0.0',
  title: '第七码头',
  description: '台风夜、停电与旧事故交织的六人现实推理本。',
  publicContext: '2026年9月，第七码头7号仓正在举办八年前事故纪念展。21:51仓库突然停电，22:10恢复。22:18场馆主人罗行被发现死在自动落锁的控制室。所有人都在22:02听见走廊广播里罗行说“展览继续，别因为停电慌张”。警方因台风无法及时到场，六名相关者必须先还原真相。',
  roles: [
    {
      id:'shen-yan', name:'沈砚', age:32, gender:'男', occupation:'纪录片导演',
      publicProfile:'八年前拍摄过第七码头事故纪录片，今晚受邀补拍纪念展。',
      privateStory:'你一直怀疑八年前的坍塌并非单纯事故。21:38你进入罗行办公室偷走一页旧账本复印件；21:42经过控制室时确认罗行仍活着。',
      knownFacts:['21:42罗行仍活着。'],
      secrets:['21:38进入过罗行办公室。','偷走一页旧账本复印件。'],
      goals:['查清八年前事故真相。','尽量隐瞒偷账本。','找出凶手。'],
      relationships:['陈泊：你曾采访过他，知道他恨罗行。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
    {
      id:'lin-xia', name:'林夏', age:29, gender:'女', occupation:'策展人',
      publicProfile:'纪念展策展人，也是罗行同父异母的妹妹。',
      privateStory:'你知道哥哥罗行参与侵吞事故赔偿。21:45你从策展终端关闭摄像头，目的是复制旧影像，计划22:15恢复。你没有切断供电。',
      knownFacts:['21:45摄像头是你主动关闭的。'],
      secrets:['准备公开罗行侵吞赔偿的旧影像。','20:50曾与罗行争吵。'],
      goals:['解释关监控不等于制造停电。','保护母亲。','找出凶手。'],
      relationships:['许澄：你曾匿名给她赔偿名单。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
    {
      id:'zhou-qi', name:'周启', age:41, gender:'男', occupation:'电工',
      publicProfile:'负责纪念展临时供电的码头电工。',
      privateStory:'为了省时间，你下午违规旁路一段老化保护线路。21:51线路过热导致总保护跳闸。你一直在配电间抢修，还伪造过维护记录。贺川下午曾问过断电时控制室机械门锁是否还能打开。',
      knownFacts:['21:51停电是线路过热触发保护。','贺川问过机械钥匙。'],
      secrets:['违规旁路线路。','伪造过维护记录。'],
      goals:['承认违规但证明自己不是凶手。','说明停电是意外。','找出利用停电的人。'],
      relationships:['贺川：下午问过断电时门锁如何工作。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
    {
      id:'chen-bo', name:'陈泊', age:45, gender:'男', occupation:'前码头工人代表',
      publicProfile:'八年前事故中失去弟弟，长期追究罗行责任。',
      privateStory:'21:28你在露台威胁罗行“再不认账就让你付代价”，21:34离开后去仓库外抽烟。你身上带着弟弟留下的旧扳手。',
      knownFacts:['你21:28公开威胁过罗行。'],
      secrets:['随身带着沉重旧扳手。','曾收过又退回封口补偿。'],
      goals:['证明威胁不等于杀人。','推动旧事故公开。','找出真正凶手。'],
      relationships:['周启：多年工友。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
    {
      id:'xu-cheng', name:'许澄', age:34, gender:'女', occupation:'保险调查员',
      publicProfile:'受遇难者家属委托重新核查八年前事故赔付。',
      privateStory:'21:47你在档案室未经授权扫描文件。21:58左右你听见控制室方向有一次很清楚的门锁声，但没看到人。',
      knownFacts:['21:58左右控制室方向有一次门锁声。','异常赔款与航运法律服务有关。'],
      secrets:['未经授权复制保险档案。'],
      goals:['保护调查证据。','厘清21:58门锁声。','推动旧案重查。'],
      relationships:['贺川：你曾向他所在律所发过异常赔款询证函。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
    {
      id:'he-chuan', name:'贺川', age:38, gender:'男', occupation:'航运法律顾问',
      publicProfile:'海岚航运法律顾问，负责第七码头旧事故善后合同。',
      privateStory:'你就是凶手。八年前你协助罗行把航运回扣伪装成赔偿和法律服务费。罗行决定第二天交出完整账本。21:51停电后，你用自己保管的应急钥匙进入控制室，21:53用展柜铜制缆针刺杀罗行。搏斗中右袖被抓破。21:56你设置22:02播放彩排录音制造存活假象，21:58离开并重新粘好钥匙封套。',
      knownFacts:['你使用应急钥匙进入控制室。','你设置22:02定时录音。'],
      secrets:['你是凶手。','用铜制缆针杀人。','八年前与罗行共同洗账。'],
      goals:['隐瞒使用应急钥匙。','把怀疑引向关监控、停电或公开威胁。','对袖口破损给出合理解释。'],
      relationships:['罗行：长期利益同盟，最近因罗行准备自首而决裂。'],
      deceptionPolicy:{mayHideOwnFacts:true,mayLieAboutOwnActions:true,forbiddenWorldFabrication:true},
    },
  ],
  locations:[
    {id:'control-room',name:'控制室',description:'尸体所在地，门禁、电脑和广播系统都在这里。'},
    {id:'office',name:'罗行办公室',description:'存放旧事故合同、账本和个人文件。'},
    {id:'exhibition',name:'纪念展厅',description:'陈列八年前码头事故遗物和展品。'},
    {id:'power-room',name:'配电间',description:'临时供电系统和维修记录所在地。'},
  ],
  clues:[
    {id:'autopsy',title:'初步尸检',roundId:'search-1',locationId:'control-room',content:'死亡时间约21:52—21:59；伤口为窄而深的三角形贯穿伤；右手指甲内有深蓝羊毛与银色细丝。',revealPolicy:'forced_public'},
    {id:'door-log',title:'机械门锁记录',roundId:'search-1',locationId:'control-room',content:'停电期间刷卡失效，但独立机械触发器记录21:53开启、21:58闭合。',revealPolicy:'owner_decides'},
    {id:'camera-log',title:'监控日志',roundId:'search-1',locationId:'office',content:'21:45策展终端主动关闭摄像头至22:15；该操作不影响供电和门禁。',revealPolicy:'owner_decides'},
    {id:'power-log',title:'配电保护记录',roundId:'search-1',locationId:'power-room',content:'21:51总保护因违规旁路线路过热跳闸，并非有人主动拉闸。',revealPolicy:'forced_public'},
    {id:'wrench',title:'陈泊的旧扳手',roundId:'search-1',locationId:'exhibition',content:'扳手无新鲜血迹，形状也与三角形伤道不符。',revealPolicy:'owner_decides'},
    {id:'visitor-log',title:'办公室访客登记',roundId:'search-1',locationId:'office',content:'21:36后办公室门锁有一次短暂开启，但没有留下刷卡身份。',revealPolicy:'owner_decides'},
    {id:'display-photo',title:'展柜布置照片',roundId:'search-1',locationId:'exhibition',content:'18:00拍摄的布展照片显示铜制缆针原本位于展柜中央，案发后位置略有偏移。',revealPolicy:'owner_decides'},
    {id:'key',title:'封存应急钥匙',roundId:'search-2',locationId:'office',content:'控制室第二把应急钥匙由贺川保管。封套有新胶覆盖旧封条，钥匙柄近期被擦拭。',revealPolicy:'owner_decides'},
    {id:'audio',title:'22:02广播任务',roundId:'search-2',locationId:'control-room',content:'广播文件来自18:13彩排录音；21:56有人在控制室电脑本机设置22:02定时播放。',revealPolicy:'forced_public'},
    {id:'fiber',title:'衣料比对',roundId:'search-2',locationId:'exhibition',content:'死者指甲中的深蓝羊毛与银色导电丝和贺川右袖材质一致，右袖有新鲜撕裂。',revealPolicy:'owner_decides'},
    {id:'weapon',title:'铜制缆针',roundId:'search-2',locationId:'exhibition',content:'展柜旧式铜制缆针缝隙检出罗行血迹，三角形尖端与伤道吻合。',revealPolicy:'forced_public'},
    {id:'draft',title:'罗行未发送邮件',roundId:'search-2',locationId:'office',content:'罗行准备次日向警方提交完整账本，正文提到“H.C.负责把钱洗进法律服务费”。',revealPolicy:'owner_decides'},
    {id:'power-question',title:'维修便签',roundId:'search-2',locationId:'power-room',content:'周启的维修本上记着：下午贺川专门问过“断电后控制室机械钥匙还能不能开门”。',revealPolicy:'owner_decides'},
    {id:'computer-login',title:'控制室本机记录',roundId:'search-2',locationId:'control-room',content:'21:56设置定时广播时没有远程登录记录，操作必须在控制室电脑本机完成。',revealPolicy:'owner_decides'},
  ],
  rounds:[
    {id:'introduction',type:'discussion',mode:'ordered',allowedTools:['send_message']},
    {id:'discussion-1',type:'discussion',mode:'free',allowedTools:[...discussionTools]},
    {id:'search-1',type:'search',actionsPerPlayer:1,allowedTools:['search_clue','reveal_clue','keep_clue_private','finish_search']},
    {id:'discussion-2',type:'discussion',mode:'free',allowedTools:[...discussionTools]},
    {id:'search-2',type:'search',actionsPerPlayer:1,allowedTools:['search_clue','reveal_clue','keep_clue_private','finish_search']},
    {id:'final-discussion',type:'discussion',mode:'free',allowedTools:[...discussionTools]},
    {id:'vote',type:'vote',allowedTools:['submit_vote']},
    {id:'reveal',type:'reveal',allowedTools:[]},
  ],
  truth:{
    murdererRoleId:'he-chuan',
    content:'八年前罗行与贺川共同把航运回扣伪装成赔偿和法律服务费。罗行准备第二天交出完整账本自保，贺川决定灭口。21:51意外停电给了机会；21:53贺川用自己保管的机械应急钥匙进入控制室，以展厅铜制缆针刺杀罗行，搏斗中右袖被抓破。21:56他设置22:02播放彩排录音制造罗行仍活着的假象；21:58离开后门自动落锁，再重新粘好钥匙封套。',
  },
}
